### ISSUE TITLE
vite-plugin-lang-jsx 对使用到 空值合并运算符 的代码会报错

### ISSUE THREAD

**Issue by Tarkpak** [caoxiemeihao/vite-plugins#10]
![image](https://user-images.githubusercontent.com/69468174/159450669-14b89938-dec5-4994-b40a-1598fe94499b.png)

**Comment by caoxiemeihao** [comment]
vite-plugin-lang-jsx@1.3.3
试试看，有个童鞋提了个 PR https://github.com/caoxiemeihao/vite-plugins/pull/11
