### ISSUE TITLE
TS2307: Cannot find module 'vite-plugin-dynamic-import' or its corresponding type declarations.

### ISSUE THREAD

**Issue by frm-037** [caoxiemeihao/vite-plugins#14]
In my `vite.config.ts` i do the following:
```ts
import dynamicImport from 'vite-plugin-dynamic-import';
```
This gives me the TS2307;

Probably a problem in `npm run build`.

**Comment by caoxiemeihao** [comment]
Hey! 👋
You can try [vite-plugin-dynamic-import@0.6.0](https://github.com/caoxiemeihao/vite-plugins/commit/3bf50dfb261fc53c25dca00069387ab496db95df), which may fixed the BUG. 🐞
