### ISSUE TITLE
vite-plugin-dynamic-import 为啥不支持 import(`@/views/${variable}.vue`) 了呢？

### ISSUE THREAD

**Issue by yangyanhui1217** [caoxiemeihao/vite-plugins#18]
我记得 0.1.1版本是支持 import(`@/views/${variable}.js`) 这种导入方式的，为啥后边的版本不支持了呢？

**Comment by caoxiemeihao** [comment]
支持的呀~兄弟！  
https://github.com/caoxiemeihao/vite-plugins/blob/d8d17a1eac0450857c6bf788066792da4d82b37a/playground/vite-plugin-dynamic-import/src/main.ts#L3

会生成  
```js
const { msg } = await __variableDynamicImportRuntime0__(`@/views/${id}.js`);

// --------- ${PLUGIN_NAME} ---------

function __variableDynamicImportRuntime0__(path) {
  switch (path) {
    case '@/views/foo.js':
      return import('/src/views/foo.js');

    default: return new Promise(function(resolve, reject) {
      (typeof queueMicrotask === 'function' ? queueMicrotask : setTimeout)(
        reject.bind(null, new Error("Unknown variable dynamic import: " + path))
      );
    })
  }
}
```

**Comment by caoxiemeihao** [comment]
你可以把 playground 拉下来自己跑跑试试  

https://github.com/caoxiemeihao/vite-plugins/tree/main/playground/vite-plugin-dynamic-import

<img width="791" alt="image" src="https://user-images.githubusercontent.com/26263658/162594809-21d22b82-c8b0-49a4-b662-b313bdf740b8.png">

**Comment by yangyanhui1217** [comment]
> 你可以把 playground 拉下来自己跑跑试试
> 
> https://github.com/caoxiemeihao/vite-plugins/tree/main/playground/vite-plugin-dynamic-import
> 
> <img alt="image" width="791" src="https://user-images.githubusercontent.com/26263658/162594809-21d22b82-c8b0-49a4-b662-b313bdf740b8.png">

好，我试试

**Comment by yangyanhui1217** [comment]
> 支持的呀~兄弟！
> 
> https://github.com/caoxiemeihao/vite-plugins/blob/d8d17a1eac0450857c6bf788066792da4d82b37a/playground/vite-plugin-dynamic-import/src/main.ts#L3
> 
> 会生成
> 
> ```js
> const { msg } = await __variableDynamicImportRuntime0__(`@/views/${id}.js`);
> 
> // --------- ${PLUGIN_NAME} ---------
> 
> function __variableDynamicImportRuntime0__(path) {
>   switch (path) {
>     case '@/views/foo.js':
>       return import('/src/views/foo.js');
> 
>     default: return new Promise(function(resolve, reject) {
>       (typeof queueMicrotask === 'function' ? queueMicrotask : setTimeout)(
>         reject.bind(null, new Error("Unknown variable dynamic import: " + path))
>       );
>     })
>   }
> }
> ```

场景：生成动态路由的.jsx文件
我刚去debugger了一下，压根没走到你说的这一步呀，dynamicImportRecords 最后还是空数组，以下是我debugger过程中的截图，求指教:
windows:
<img width="686" alt="1649559208986_A970F983-FCF6-4a18-B99B-3BA869663D39" src="https://user-images.githubusercontent.com/94613177/162600031-8f7fcfc2-d88c-4151-bc28-c38c3d820c39.png">

mac:
![lQDPDhtRXR1yDXDNAozNB4KwzOnDG06yCLoCVfrCqsAoAA_1922_652](https://user-images.githubusercontent.com/94613177/162600068-9f482d5e-fda3-439f-8cb1-38ee061ce2f1.jpg)

**Comment by caoxiemeihao** [comment]
你直接提供最小复现的代码推到 github 吧，你这么截张图我也没本事看透

**Comment by yangyanhui1217** [comment]
> 你直接提供最小复现的代码推到 github 吧，你这么截张图我也没本事看透

嗯嗯，刚写好demo 准备推上去，然后就发现问题了，我这边 `import(`@/views/${item.component}.vue`)` 里面的 `item.component` 是个子路径，所以这个插件内容用 `../views/*.vue` 方式是读取不到 `views` 下边的孙子文件。所以，大佬，你看看，要不要兼容一下呢，这描述清楚不，还需要demo吗？

**Comment by caoxiemeihao** [comment]
支持子孙嵌套的，你看看这块源码，是处理了子孙，有个 `deep = true`

https://github.com/caoxiemeihao/vite-plugins/blob/d8d17a1eac0450857c6bf788066792da4d82b37a/packages/dynamic-import/src/dynamic-import-vars.ts#L171

```js
/**
 * ```
 * 🚧 In some cases, glob may not be available  
 * e.g. fill necessary slash  
 * `./views*` -> `./views/*`
 * `./views*.js` -> `./views/*.js`
 * ```
 */
export function tryFixGlobSlash(glob: string, deep = true): string | void {
  const extname = path.extname(glob)
  // It could be `./views*.js`, which needs to be repaired to `./views/*.js`
  glob = glob.replace(extname, '')

  const [, importPath] = glob.match(/(.*\w\/?)\*/)
  if (!importPath.endsWith('/')) {
    // fill necessary slash
    // `./views*` -> `./views/*`
    let fixedGlob = glob.replace(importPath, importPath + '/')

    fixedGlob = deep
      // match as far as possible
      // `./views/*` -> `./views/**/*`
      ? fixedGlob.replace(/^(.*)\/\*$/, '$1/**/*')
      : fixedGlob

    // if it has a '.js' extension
    // `./views/*` -> `./views/*.js`
    fixedGlob += extname

    return fixedGlob
  }
}
```

再看下这个生成后的文件

https://github.com/caoxiemeihao/vite-plugins/blob/d8d17a1eac0450857c6bf788066792da4d82b37a/playground/vite-plugin-dynamic-import/src/main-generated.js#L18

```js
function __variableDynamicImportRuntime4__(path) {
  switch (path) {
    case './views/baz/index.tsx':
      return import('./views/baz/index.tsx');

    case './views/nested/nesting-dir/index.tsx':
      return import('./views/nested/nesting-dir/index.tsx');

    default: return new Promise(function(resolve, reject) {
      (typeof queueMicrotask === 'function' ? queueMicrotask : setTimeout)(
        reject.bind(null, new Error("Unknown variable dynamic import: " + path))
      );
    })
  }
}
```

**Comment by caoxiemeihao** [comment]
要是还不行，你就贴 demo 吧

**Comment by yangyanhui1217** [comment]
> 要是还不行，你就贴 demo 吧

大佬，不好意思啊，我刚才才发现我的标题贴错了，我上边跟你一直讨论的是 vite+vue2项目里面是否支持.vue文件的动态引入呢

**Comment by caoxiemeihao** [comment]
> 大佬，不好意思啊，我刚才才发现我的标题贴错了，我上边跟你一直讨论的是 vite+vue2项目里面是否支持.vue文件的动态引入呢

没区别啊，这个插件对 vue2 版本无感知，只是工作在 vite 下

**Comment by yangyanhui1217** [comment]
> > 大佬，不好意思啊，我刚才才发现我的标题贴错了，我上边跟你一直讨论的是 vite+vue2项目里面是否支持.vue文件的动态引入呢
> 
> 没区别啊，这个插件对 vue2 版本无感知，只是工作在 vite 下

切了个分支

**Comment by yangyanhui1217** [comment]
> > 大佬，不好意思啊，我刚才才发现我的标题贴错了，我上边跟你一直讨论的是 vite+vue2项目里面是否支持.vue文件的动态引入呢
> 
> 没区别啊，这个插件对 vue2 版本无感知，只是工作在 vite 下
demo：
playground/vite-plugin-dynamic-import下边的views下边创建base/home/index.vue文件， 然后在index.html里面添加个class为test-vue的div元素，然后main.ts文件里面测试代码，如下
```
async function setView7(id: string) {
    // After `expressiontoglob` processing, it may become a normal path
    const { msg } = await import(`@/views/${id}.vue`)
    document.querySelector('.view')!.innerHTML = msg
}

const views7 = {
    'test-vue': () => setView7('base/home/index'),
}
Object.entries(views7).forEach(([className, cb]) => {
    document.querySelector(`.${className}`)!.addEventListener('click', cb)
})
```
不知道是我哪里操作不对

**Comment by caoxiemeihao** [comment]
```js
// 在 @rollup/plugin-dynamic-import-var 被认为是一个正常的 importee
import(`@/views/${id}.vue`) //  -> `./views/*.vue`

// 这种少了个 / 的才需要修复
import(`@/views${id}.vue`) //  -> `./views/**/*.vue`
```

至于你说的 `@0.1.1` 时候支持，现在不支持；是因为在 `@0.1.1` 时候很暴力，无脑将 `/*` 变成 `/**/*`   
这个功能可以加回来，不过要在 README 中说明；后期提供选项支持用户决定要不要开启这个功能  
因为过渡的 `/**/*` 会使得生成的代码量变大，打包也会变大

**Comment by yangyanhui1217** [comment]
> ```js
> // 在 @rollup/plugin-dynamic-import-var 被认为是一个正常的 importee
> import(`@/views/${id}.vue`) //  -> `./views/*.vue`
> 
> // 这种少了个 / 的才需要修复
> import(`@/views${id}.vue`) //  -> `./views/**/*.vue`
> ```
> 
> 至于你说的 `@0.1.1` 时候支持，现在不支持；是因为在 `@0.1.1` 时候很暴力，无脑将 `/*` 变成 `/**/*` 这个功能可以加回来，不过要在 README 中说明；后期提供选项支持用户决定要不要开启这个功能 因为过渡的 `/**/*` 会使得生成的代码量变大，打包也会变大

嗯嗯，好的

**Comment by caoxiemeihao** [comment]
# vite-plugin-dynamic-import@0.8.0

## Feature

- 默认支持深层查找 https://github.com/caoxiemeihao/vite-plugins/commit/22a24d34ad0479a9be1fa2cdcacc444abec40b45
- 兼容 windows 绝对路径 https://github.com/caoxiemeihao/vite-plugins/commit/aacb0fd7c08004b83dea106baa5d8e226146d87e

**Comment by caoxiemeihao** [comment]
@yangyanhui1217 
我看着你里用 windows 时候相对路径计算的不对，哪有 glob 一大长串的；`0.8.0` 尝试兼容了这个问题；  
我手里没 windows，你再 `debug` 一下看看 glob 正常了没。  

正常的应该就是 `../src` 这种很短的相对路径。

![](https://user-images.githubusercontent.com/94613177/162600031-8f7fcfc2-d88c-4151-bc28-c38c3d820c39.png)

---

还有个问题，你这个 debug 是怎么弄的；教下我，我很少用这东西不知道怎么配置

**Comment by yangyanhui1217** [comment]
> @yangyanhui1217 我看着你里用 windows 时候相对路径计算的不对，哪有 glob 一大长串的；`0.8.0` 尝试兼容了这个问题； 我手里没 windows，你再 `debug` 一下看看 glob 正常了没。
> 
> 正常的应该就是 `../src` 这种很短的相对路径。
> 
> ![](https://user-images.githubusercontent.com/94613177/162600031-8f7fcfc2-d88c-4151-bc28-c38c3d820c39.png)
> 
> 还有个问题，你这个 debug 是怎么弄的；教下我，我很少用这东西不知道怎么配置

1. 好，我去拉一下最新的包测一下
2. 如何使用debug工具
vscode 里面的 JavaScript Debug Terminal打开，正常执行命令即可。
图一打开 JavaScript Debug Terminal 的地方：
![image](https://user-images.githubusercontent.com/94613177/162865046-85654848-fcd3-41fb-b6df-f266b855c997.png)
图二是怎么打断点：
![image](https://user-images.githubusercontent.com/94613177/162865372-fcc9f0a7-ec51-4ac3-9a8a-2bd991bc26da.png)

**Comment by yangyanhui1217** [comment]
@caoxiemeihao 为啥我下载不下来0.8.0版本
![image](https://user-images.githubusercontent.com/94613177/162868358-b9e5277d-2ca7-47b6-9069-3ab99bc9655f.png)

**Comment by caoxiemeihao** [comment]
你用了 npm 镜像？我这可以下载下来

**Comment by yangyanhui1217** [comment]
> 你用了 npm 镜像？我这可以下载下来

我卸载又重装好了，更新没用

**Comment by caoxiemeihao** [comment]
怎么可能，你直接贴 Demo 仓库吧

```js
const views7 = {
  "test-vue": () => setView7("base/home/index")
};async function setView7(id) {
  const { msg } = await __variableDynamicImportRuntime5__(`@/views/${id}.vue`);
  document.querySelector(".view").innerHTML = msg;
}
const views7 = {
  "test-vue": () => setView7("base/home/index")
};
```

```js

function __variableDynamicImportRuntime5__(path) {
  switch (path) {
    case '@/views/base/home/index.vue':
      return import('/src/views/base/home/index.vue');

    default: return new Promise(function(resolve, reject) {
      (typeof queueMicrotask === 'function' ? queueMicrotask : setTimeout)(
        reject.bind(null, new Error("Unknown variable dynamic import: " + path))
      );
    })
  }
}
```

**Comment by yangyanhui1217** [comment]
@caoxiemeihao windows现在好了
![image](https://user-images.githubusercontent.com/94613177/162885389-3be49f84-8eb1-40fc-ae01-5340e74339dd.png)

----

草鞋没号：你这个 `../views/**/*.vue` 是深度的 glob 啊

**Comment by yangyanhui1217** [comment]
> @caoxiemeihao windows现在好了 ![image](https://user-images.githubusercontent.com/94613177/162885389-3be49f84-8eb1-40fc-ae01-5340e74339dd.png)
> 
> 草鞋没号：你这个 `../views/**/*.vue` 是深度的 glob 啊

`../views/*.vue` 也是好的

<img width="697" alt="1649745121206_8AF893C6-503A-40ab-B7DB-0397B7C9FECC" src="https://user-images.githubusercontent.com/94613177/162896687-63385b07-8128-4a92-bfff-1452baefc989.png">

**Comment by yangyanhui1217** [comment]
> 怎么可能，你直接贴 Demo 仓库吧
> 
> ```js
> const views7 = {
>   "test-vue": () => setView7("base/home/index")
> };async function setView7(id) {
>   const { msg } = await __variableDynamicImportRuntime5__(`@/views/${id}.vue`);
>   document.querySelector(".view").innerHTML = msg;
> }
> const views7 = {
>   "test-vue": () => setView7("base/home/index")
> };
> ```
> 
> ```js
> function __variableDynamicImportRuntime5__(path) {
>   switch (path) {
>     case '@/views/base/home/index.vue':
>       return import('/src/views/base/home/index.vue');
> 
>     default: return new Promise(function(resolve, reject) {
>       (typeof queueMicrotask === 'function' ? queueMicrotask : setTimeout)(
>         reject.bind(null, new Error("Unknown variable dynamic import: " + path))
>       );
>     })
>   }
> }
> ```

这个不是已经好了吗？怎么？

---

草鞋没号：你不更新了没用么  

<img width="327" alt="image" src="https://user-images.githubusercontent.com/26263658/162898891-60eb2d48-10d7-478b-a22c-e82498529bfa.png">

---

草鞋没号：直接 `npm i` 装不会更新中间的版本号，只会更新最后面的小版本号；要么 `npm uninstall` 后重装，要么手动更版本号

**Comment by yangyanhui1217** [comment]
> > 怎么可能，你直接贴 Demo 仓库吧
> > ```js
> > const views7 = {
> >   "test-vue": () => setView7("base/home/index")
> > };async function setView7(id) {
> >   const { msg } = await __variableDynamicImportRuntime5__(`@/views/${id}.vue`);
> >   document.querySelector(".view").innerHTML = msg;
> > }
> > const views7 = {
> >   "test-vue": () => setView7("base/home/index")
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```js
> > function __variableDynamicImportRuntime5__(path) {
> >   switch (path) {
> >     case '@/views/base/home/index.vue':
> >       return import('/src/views/base/home/index.vue');
> > 
> >     default: return new Promise(function(resolve, reject) {
> >       (typeof queueMicrotask === 'function' ? queueMicrotask : setTimeout)(
> >         reject.bind(null, new Error("Unknown variable dynamic import: " + path))
> >       );
> >     })
> >   }
> > }
> > ```
> 
> 这个不是已经好了吗？怎么？
> 
> 草鞋没号：你不更新了没用么
> 
> <img alt="image" width="327" src="https://user-images.githubusercontent.com/26263658/162898891-60eb2d48-10d7-478b-a22c-e82498529bfa.png">
> 
> 草鞋没号：直接 `npm i` 装不会更新中间的版本号，只会更新最后面的小版本号；要么 `npm uninstall` 后重装，要么手动更版本号

嗯嗯，已经卸载 重装好了

**Comment by caoxiemeihao** [comment]
没啥问题，关 issues 了 :)
