### ISSUE TITLE
'src/' 这种别名会报错  在项目例子中

### ISSUE THREAD

**Issue by a982246809** [caoxiemeihao/vite-plugins#19]
![image](https://user-images.githubusercontent.com/56909676/163142873-f72015d9-518d-4a38-9ee1-9613bea410f8.png)
![image](https://user-images.githubusercontent.com/56909676/163142924-d5292eea-e10b-42ec-a1dc-4f4d38412fb3.png)
![image](https://user-images.githubusercontent.com/56909676/163142990-fa5eb17f-0ff6-41d6-aad5-9e98df2b7c8e.png)

**Comment by caoxiemeihao** [comment]
你换到英文的目录试试，可能 @rollup/plugin-dynaimic-import-var 不支持中文  
这是 demo 转换后的代码  
https://github.com/caoxiemeihao/vite-plugins/blob/main/playground/vite-plugin-dynamic-import/src/main-generated.js

**Comment by a982246809** [comment]
还是一样的  
![image](https://user-images.githubusercontent.com/56909676/163295832-1e35be14-5df0-453d-9ddd-1186a57cbf9c.png)
注释掉就好了

**Comment by caoxiemeihao** [comment]
> 还是一样的  
> ![image](https://user-images.githubusercontent.com/56909676/163295832-1e35be14-5df0-453d-9ddd-1186a57cbf9c.png)
> 注释掉就好了

啥都没改就报错？其他的几个 `import()` 没问题？就这个不行？  
我用的 mac 没复现出来这个问题 

---

Windows 下 `path.join` 拼接的文件应该是 `\\` 这种；你试试吧 vite.config.ts 中的 `path.join` 换成 `path.posix.join` 应该就好了

**Comment by caoxiemeihao** [comment]
已修复 https://github.com/caoxiemeihao/vite-plugins/commit/e845046fc9c7a885b474fa5272ea12b800939c34
