### ISSUE TITLE
[Question] If I write number comparison like `a<b` ?  Will this `.vue` file be marked as JSX ?

### ISSUE THREAD

**Issue by chenxxzhe** [caoxiemeihao/vite-plugins#3]

**Comment by caoxiemeihao** [comment]
Yes. This judgment is not rigorous enough, I plan to fix it in the next version.

**Comment by caoxiemeihao** [comment]
更可靠的方式需要使用 语法分析了，不过会消耗一些性能
其次 `a<b` 这种代码被加上了 `lang="jsx"`，按理说也不会影响使用

**Comment by caoxiemeihao** [comment]
新版本已经用 `ast` 语法解析了 https://www.npmjs.com/package/vite-plugin-lang-jsx/v/1.2.0
