### ISSUE TITLE
vite-plugin-esmodule seems broken

### ISSUE THREAD

**Issue by nosferatu500** [caoxiemeihao/vite-plugins#30]
Hi! I have that #9 issue again. (v1.2.5)

On version v1.2.4 everything fine.
Roll back on this version for now.

**Comment by caoxiemeihao** [comment]
`v1.2.4` and `v1.2.5` have little change.  
This and #9 is not the same.  

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/26263658/168058707-75ba697a-459d-492a-8379-27ef71b88514.png">

**Comment by nosferatu500** [comment]
I see, but when I'm using v1.2.5 I'm still getting an error "getDefaultExportFromCjs is not a function".

**Comment by caoxiemeihao** [comment]
Can you show me a Demo?

**Comment by nosferatu500** [comment]
Sorry I was too busy. I will try to send you an example next week.

**Comment by caoxiemeihao** [comment]
https://github.com/vite-plugin/vite-plugin-esmodule
