### ISSUE TITLE
Error: Uncaught TypeError: Cannot read properties of undefined (reading 'default')

### ISSUE THREAD

**Issue by Stanzilla** [caoxiemeihao/vite-plugins#36]
Hey there, I'm trying to update our app to use vite and tried using `vite-plugin-fast-external`. You might remember me from previous tickets and yes, we still haven't gotten our app working yet with Vite.

```
__fast-external:vue:3 Uncaught TypeError: Cannot read properties of undefined (reading 'default')
    at __fast-external:vue:3:17
(anonymous) @ __fast-external:vue:3
```

I'm getting the above error when I'm using this branch https://github.com/WeakAuras/WeakAuras-Companion/tree/v5 and the following changes: 
<img width="722" alt="Fork-2022-08-12-17 39 28" src="https://user-images.githubusercontent.com/75278/184390834-003cf5f1-a352-49bd-8c56-b9f18c3a8d64.png">

Any help would be appreciated, thanks :)

**Comment by caoxiemeihao** [comment]
Hey 👋 I remember you, my good friend!
Using external means you have to provide a CND link for it to work correctly.
I submitted a PR, I hope it helps you. https://github.com/WeakAuras/WeakAuras-Companion/pull/1525

**Comment by Stanzilla** [comment]
Oh awesome, thank you so much!
