### ISSUE TITLE
vite-plugin-commonjs 使用后报错

### ISSUE THREAD

**Issue by hujinbin** [caoxiemeihao/vite-plugins#8]
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/23625357/158765570-98e36d53-f994-42e2-98df-8eaf2aedf6b6.png">

**Comment by caoxiemeihao** [comment]
vite-plugin-commonjs 重构中。。。

**Comment by vcxiaohan** [comment]
![image](https://user-images.githubusercontent.com/13744878/160443258-14b9dbfb-b6fa-446b-913e-2894e5dca092.png)
这个是插件执行顺序不当引起的错误，你需要把它放到 vue 的插件后面  
重构后会自动排序

**Comment by caoxiemeihao** [comment]
Hey! 👋 @hujinbin @vcxiaohan 
代码已经移至 ☞ [vite-plugin-commonjs](https://github.com/vite-plugin/vite-plugin-commonjs)  
重构持续中，持续关注。。。
